# Generated by Django 4.2.4 on 2026-02-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('app', 'App'), ('card', 'Card'), ('web', 'Web')], default='web', max_length=10),
        ),
    ]
