# Generated by Django 4.2.4 on 2026-02-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('mobile', 'mobile'), ('both', 'both'), ('web', 'web')], default='both', max_length=10),
        ),
    ]
